[package]
name = "giga_grabber"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.23.0", features = ["rt", "macros", "sync", "rt-multi-thread"] }
mega = { path = "mega-rs" }
reqwest = { version = "0.11.13", default-features = false, features = ["socks"] }
fastrand = "1.7.0"
futures = "0.3.28"
tokio-util = "0.7.7"
structopt = "0.3.26"
indicatif = "0.17.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
