[package]
name = "giga_grabber"
version = "1.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", default-features = false, features = ["sync"] }
mega = { path = "mega-rs" }
reqwest = { version = "0.12", default-features = false, features = ["socks"] }
fastrand = "2"
futures = "0.3"
tokio-util = "0.7"
deadqueue = "0.2"
iced = { version = "0.9.0", features = ["tokio", "canvas", "svg"] }
iced_native = "0.10.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
num-traits = "0.2"
dark-light = "1"
native-dialog = "0.7"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
